### ISSUE TITLE
Get-LabHostConfiguration : Erroring out

### ISSUE THREAD

**Issue by DexterPOSH** [VirtualEngine/Lability#62]
In the newer Module version '0.9.2' , the function Get-LabHostConfiguration is spewing out error.
IMO this is because of the change in the Get-WindowsFeatureTargetResource, which leads to GetDSCResource Function erroring out. Below is a snippet of the GetDSCResource function (line 72-75 from Lib\DSCResource.ps1) which are failing.

```PowerShell
$getTargetResourceCommand = 'Get-{0}TargetResource' -f $ResourceName;
 WriteVerbose ($localized.InvokingCommand -f $getTargetResourceCommand);
 $Parameters.Remove('Ensure');
 return (& $getTargetResourceCommand @Parameters);
```

Below is the what I see when I run the function :
```PowerShell
PS>Get-LabHostConfiguration 
Import-Module : The specified module 'C:\Users\Administrator\Documents\GitHub\Lab\DSCResources\PSDesiredStateConfiguration\DSCResources\MSFT_RoleResource\MSFT_RoleResource.psm1' was 
not loaded because no valid module file was found in any module directory.
At C:\Users\Administrator\Documents\GitHub\Lab\Lib\DscResource.ps1:43 char:17
+ ...             Import-Module -Name $resourcePath -Prefix $Prefix -Force  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\Admini...leResource.psm1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
& : The term 'Get-WindowsFeatureTargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At C:\Users\Administrator\Documents\GitHub\Lab\Lib\DscResource.ps1:75 char:19
+         return (& $getTargetResourceCommand @Parameters);
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WindowsFeatureTargetResource:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Import-Module : The specified module 'C:\Users\Administrator\Documents\GitHub\Lab\DSCResources\PSDesiredStateConfiguration\DSCResources\MSFT_RoleResource\MSFT_RoleResource.psm1' was 
not loaded because no valid module file was found in any module directory.
At C:\Users\Administrator\Documents\GitHub\Lab\Lib\DscResource.ps1:43 char:17
+ ...             Import-Module -Name $resourcePath -Prefix $Prefix -Force  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Users\Admini...leResource.psm1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
& : The term 'Get-WindowsFeatureTargetResource' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, 
verify that the path is correct and try again.
At C:\Users\Administrator\Documents\GitHub\Lab\Lib\DscResource.ps1:75 char:19
+         return (& $getTargetResourceCommand @Parameters);
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WindowsFeatureTargetResource:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
WARNING: Unable to query CCM_ClientUtilities: Invalid namespace 

Name                           Value                                                                                                                                                               
----                           -----                                                                                                                                                               
PendingFileRename              False                                                                                                                                                               
Name                           TestingForHypervReboot                                                                                                                                              
PendingComputerRename          False                                                                                                                                                               
ComponentBasedServicing        False                                                                                                                                                               
WindowsUpdate                  False                                                                                                                                                               
CcmClientSDK                   False                                                                                                                                                               


```

**Comment by DexterPOSH** [comment]
If anyone else confirms the same behavior, I can raise a PR.
Fixed this in my Dev repo in the below commit.
[https://github.com/DexterPOSH/Lab/commit/540f080781f80e3911a73d12e7f8057e83d41218](https://github.com/DexterPOSH/Lab/commit/540f080781f80e3911a73d12e7f8057e83d41218)

**Comment by iainbrighton** [comment]
@DexterPOSH Ah! I can see what's going on here; it's trying to load the PSDesiredStateConfiguration module from %ProgramFiles% instead of the built-in %WINDIR% location.

I fixed this in my repo by changing line 92 in \Src\LabHostConfiguration.ps1 to:
```Powershell
ImportDscResource -ModuleName $configuration.ModuleName -ResourceName $configuration.ResourceName -Prefix $configuration.Prefix -UseDefault:$configuration.UseDefault;
```
Can you confirm whether this fixes it for you?

**Comment by DexterPOSH** [comment]
@iainbrighton I am still seeing the same error, I believe the issue is with the GetDSCResource but Yes the above fix should also be done :+1: 

> Get-WindowsFeatureTargetResource : A parameter cannot be found that matches parameter name 'IncludeAllSubFeature'.
At C:\Users\Administrator.LAJOLLAINFRA\Documents\GitHub\Lab\Lib\DscResource.ps1:79 char:45
+         return (& $getTargetResourceCommand @Parameters);
+                                             ~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-WindowsFeatureTargetResource], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-WindowsFeatureTargetResource

**Comment by iainbrighton** [comment]
@DexterPOSH OK - that's a different error which DexterPOSH@540f080 should fix?
